// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtRflUmwrvNgxeXqqI4g1LDQbmHWsljtg',
    appId: '1:238263015355:web:a4d2b3a157af533e8bd69e',
    messagingSenderId: '238263015355',
    projectId: 'otg-app-60736',
    authDomain: 'otg-app-60736.firebaseapp.com',
    storageBucket: 'otg-app-60736.appspot.com',
    measurementId: 'G-GDMD5D7H75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5aAsG0dwOnLIVbNwX-T-BOpEI3sns0AI',
    appId: '1:238263015355:android:e96df7fa8a0e3bba8bd69e',
    messagingSenderId: '238263015355',
    projectId: 'otg-app-60736',
    storageBucket: 'otg-app-60736.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrV2cV5ePdtEMitJBZ1ftQqt2w2KJfQsA',
    appId: '1:238263015355:ios:c73357a8cabe5d2c8bd69e',
    messagingSenderId: '238263015355',
    projectId: 'otg-app-60736',
    storageBucket: 'otg-app-60736.appspot.com',
    iosBundleId: 'com.example.appointments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrV2cV5ePdtEMitJBZ1ftQqt2w2KJfQsA',
    appId: '1:238263015355:ios:690c11726830a4ce8bd69e',
    messagingSenderId: '238263015355',
    projectId: 'otg-app-60736',
    storageBucket: 'otg-app-60736.appspot.com',
    iosBundleId: 'com.example.appointments.RunnerTests',
  );
}
